# Generated by Django 5.1.6 on 2025-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='url',
        ),
        migrations.AlterField(
            model_name='character',
            name='episode',
            field=models.ManyToManyField(blank=True, related_name='episode', to='character.episode', verbose_name='Episodio onde personagem atua'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.character', verbose_name='Personagens'),
        ),
    ]
