# Generated by Django 5.1.6 on 2025-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_episode_url_alter_character_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='episode',
            field=models.ManyToManyField(blank=True, null=True, related_name='episode', to='character.episode', verbose_name='Episodio onde personagem atua'),
        ),
    ]
