# Generated by Django 5.1.6 on 2025-03-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_character_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='characters',
        ),
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do episodio'),
        ),
    ]
