# Generated by Django 5.1.6 on 2025-03-02 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_remove_episode_characters_episode_url'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listchars',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='character.character'),
        ),
        migrations.AlterField(
            model_name='listchars',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
